baseurl = "http://kimbrerfesten.dk/"
languageCode = "da-dk"
title = "Kimbrerfesten"
author = "Niels Linnemann"
copyright = "Copyright (c) 2008 - 2020, Kimbrerfesten; all rights reserved."
canonifyurls = true
paginate = 6


theme = "hugo-kimbrer"


[params]
    surveylink = "" #"https://da.surveymonkey.com/r/JTL9R7P"
    eventDate = "D. 3. - 6. SEPTEMBER 2020"
    showmovie = false