baseurl = "http://kimbrerfesten.dk/"
languageCode = "da-dk"
title = "Kimbrerfesten"
author = "Niels Linnemann"
copyright = "Copyright (c) 2008 - 2017, Kimbrerfesten; all rights reserved."
canonifyurls = true
paginate = 6

theme = "hugo-kimbrer"


[params]
    surveylink = "" #"https://www.surveymonkey.com/r/GM7HFDB"