baseurl = "http://kimbrerfesten.dk/hugo/public/"
languageCode = "da-dk"
title = "Kimbrerfesten"
author = "Niels Linnemann"
copyright = "Copyright (c) 2008 - 2017, Kimbrerfesten; all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-kimbrer"

