baseurl = "http://kimbrerfesten.dk/hugo/public/"
languageCode = "da-dk"
title = "Kimbrerfesten"
author = "Niels Linnemann"
copyright = "Copyright (c) 2008 - 2017, Kimbrerfesten; all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-kimbrer"


[[menu.program]]
    name = "Onsdag"
    pre = ""
    weight = -100
    identifier = "onsdag"
    url = "/program/onsdag"

[[menu.program]]
    name = "Torsdag"
    pre = ""
    weight = -90
    identifier = "torsdag"
    url = "/program/torsdag"