baseurl = "http://kimbrerfesten.dk/hugo/public/"
languageCode = "da-dk"
title = "Kimbrerfesten"
author = "Niels Linnemann"
copyright = "Copyright (c) 2008 - 2017, Kimbrerfesten; all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-kimbrer"

[[menu.main]]
    name = "Om"
    pre = ""
    weight = -120
    identifier = "page"
    url = "/page/about/"

[[menu.main]]
    name = "Kontakt"
    pre = ""
    weight = -110
    identifier = "contact"
    url = "/contact/"

[[menu.main]]
    name = "Program"
    pre = ""
    weight = -100
    identifier = "program"
    url = "/program/"
    
[[menu.main]]
    name = "Onsdag"
    pre = ""
    parent = "program"
    weight = -90
    url = "/program/onsdag"

[[menu.main]]
    name = "Torsdag"
    pre = ""
    parent = "program"
    weight = -80
    url = "/program/torsdag"